### ISSUE TITLE
Update pull request checklist

### ISSUE THREAD

**Issue by MicahGale** [idaholab/MontePy#591]
Update checklist for PR:

* [ ] ensure is consistent with standards in dev docs.
* [ ] Add more details to what is expected from documentation. 
* [ ] Require coverage reports?
